/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package identificador_ip_web_servidor_menu_e_submenu;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.JOPM;
import br.com.jmary.utilidades.PopupMenu_Colar;
import identificador_ip_web_servidor.BrowserFX;
import identificador_ip_web_servidor.Email_Enviar;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.awt.BorderLayout;
import java.util.StringTokenizer;
import javafx.application.Platform;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ana
 */
public class Identificador_Ip_Web_Servidor_Submenu_01 extends javax.swing.JPanel {
    
    Exportando Exportando;
    PopupMenu_Colar PopupMenu_Colar;
    Home Home;
        
    public Identificador_Ip_Web_Servidor_Submenu_01( Home Home2 ) {
        Home = Home2;
        
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel28 = new javax.swing.JPanel();
        JPOpcao_26 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        JPOpcao_27 = new javax.swing.JPanel();
        tf_Endereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPOpcao_30 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        JPOpcao_31 = new javax.swing.JPanel();
        tf_Senha = new javax.swing.JTextField();
        JPOpcao_32 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        JPOpcao_33 = new javax.swing.JPanel();
        tf_Endereco3 = new javax.swing.JTextField();
        JPOpcao_34 = new javax.swing.JPanel();
        tf_Endereco4 = new javax.swing.JTextField();
        JPOpcao_35 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        JPOpcao_36 = new javax.swing.JPanel();
        tf_Endereco5 = new javax.swing.JTextField();
        JPOpcao_37 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        JPOpcao_38 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        JPOpcao_39 = new javax.swing.JPanel();
        tf_SenhaEmail = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1034, 71));

        JPOpcao_26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_26.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_26MousePressed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("IP do Roteador.: ");

        javax.swing.GroupLayout JPOpcao_26Layout = new javax.swing.GroupLayout(JPOpcao_26);
        JPOpcao_26.setLayout(JPOpcao_26Layout);
        JPOpcao_26Layout.setHorizontalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_26Layout.setVerticalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_27.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_27.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_27MousePressed(evt);
            }
        });

        tf_Endereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco.setText("192.168.0.1");
        tf_Endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseExited(evt);
            }
        });
        tf_Endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_EnderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_27Layout = new javax.swing.GroupLayout(JPOpcao_27);
        JPOpcao_27.setLayout(JPOpcao_27Layout);
        JPOpcao_27Layout.setHorizontalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_27Layout.setVerticalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/nuvem.png"))); // NOI18N
        jLabel1.setText("Iniciar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setText("Identificador de IP na Web - Servidor - JMarySystems");

        JPOpcao_30.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_30.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_30MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_30MousePressed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel82.setText("Senha.: ");

        javax.swing.GroupLayout JPOpcao_30Layout = new javax.swing.GroupLayout(JPOpcao_30);
        JPOpcao_30.setLayout(JPOpcao_30Layout);
        JPOpcao_30Layout.setHorizontalGroup(
            JPOpcao_30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_30Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel82)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_30Layout.setVerticalGroup(
            JPOpcao_30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_31.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_31.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_31MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_31MousePressed(evt);
            }
        });

        tf_Senha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Senha.setText("******");
        tf_Senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Senha.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_SenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_SenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_SenhaMouseExited(evt);
            }
        });
        tf_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_SenhaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_31Layout = new javax.swing.GroupLayout(JPOpcao_31);
        JPOpcao_31.setLayout(JPOpcao_31Layout);
        JPOpcao_31Layout.setHorizontalGroup(
            JPOpcao_31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_31Layout.setVerticalGroup(
            JPOpcao_31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_31Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_32.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_32MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_32MousePressed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel83.setText("Usuário.: ");

        javax.swing.GroupLayout JPOpcao_32Layout = new javax.swing.GroupLayout(JPOpcao_32);
        JPOpcao_32.setLayout(JPOpcao_32Layout);
        JPOpcao_32Layout.setHorizontalGroup(
            JPOpcao_32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPOpcao_32Layout.setVerticalGroup(
            JPOpcao_32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_33.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_33.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_33MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_33MousePressed(evt);
            }
        });

        tf_Endereco3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco3.setText("Admin");
        tf_Endereco3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco3.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Endereco3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_Endereco3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_Endereco3MouseExited(evt);
            }
        });
        tf_Endereco3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_Endereco3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_33Layout = new javax.swing.GroupLayout(JPOpcao_33);
        JPOpcao_33.setLayout(JPOpcao_33Layout);
        JPOpcao_33Layout.setHorizontalGroup(
            JPOpcao_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_33Layout.setVerticalGroup(
            JPOpcao_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_33Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_34.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_34.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_34MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_34MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_34MousePressed(evt);
            }
        });

        tf_Endereco4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco4.setText("username");
        tf_Endereco4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco4.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Endereco4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_Endereco4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_Endereco4MouseExited(evt);
            }
        });
        tf_Endereco4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_Endereco4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_34Layout = new javax.swing.GroupLayout(JPOpcao_34);
        JPOpcao_34.setLayout(JPOpcao_34Layout);
        JPOpcao_34Layout.setHorizontalGroup(
            JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_34Layout.setVerticalGroup(
            JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_34Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_35.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_35.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_35MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_35MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_35MousePressed(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel84.setText("ID Input Usuário.: ");

        javax.swing.GroupLayout JPOpcao_35Layout = new javax.swing.GroupLayout(JPOpcao_35);
        JPOpcao_35.setLayout(JPOpcao_35Layout);
        JPOpcao_35Layout.setHorizontalGroup(
            JPOpcao_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_35Layout.setVerticalGroup(
            JPOpcao_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_36.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_36.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_36MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_36MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_36MousePressed(evt);
            }
        });

        tf_Endereco5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco5.setText("password");
        tf_Endereco5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco5.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Endereco5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_Endereco5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_Endereco5MouseExited(evt);
            }
        });
        tf_Endereco5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_Endereco5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_36Layout = new javax.swing.GroupLayout(JPOpcao_36);
        JPOpcao_36.setLayout(JPOpcao_36Layout);
        JPOpcao_36Layout.setHorizontalGroup(
            JPOpcao_36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_36Layout.setVerticalGroup(
            JPOpcao_36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_36Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_37.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_37.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_37MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_37MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_37MousePressed(evt);
            }
        });

        jLabel85.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel85.setText("ID Input Senha.: ");

        javax.swing.GroupLayout JPOpcao_37Layout = new javax.swing.GroupLayout(JPOpcao_37);
        JPOpcao_37.setLayout(JPOpcao_37Layout);
        JPOpcao_37Layout.setHorizontalGroup(
            JPOpcao_37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
        );
        JPOpcao_37Layout.setVerticalGroup(
            JPOpcao_37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_38.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_38.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_38MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_38MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_38MousePressed(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel86.setText("Senha/Email.: ");

        javax.swing.GroupLayout JPOpcao_38Layout = new javax.swing.GroupLayout(JPOpcao_38);
        JPOpcao_38.setLayout(JPOpcao_38Layout);
        JPOpcao_38Layout.setHorizontalGroup(
            JPOpcao_38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_38Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel86)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_38Layout.setVerticalGroup(
            JPOpcao_38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_39.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_39.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_39MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_39MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_39MousePressed(evt);
            }
        });

        tf_SenhaEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_SenhaEmail.setText("******");
        tf_SenhaEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_SenhaEmail.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_SenhaEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_SenhaEmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_SenhaEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_SenhaEmailMouseExited(evt);
            }
        });
        tf_SenhaEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_SenhaEmailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_39Layout = new javax.swing.GroupLayout(JPOpcao_39);
        JPOpcao_39.setLayout(JPOpcao_39Layout);
        JPOpcao_39Layout.setHorizontalGroup(
            JPOpcao_39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_SenhaEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_39Layout.setVerticalGroup(
            JPOpcao_39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_39Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_SenhaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(JPOpcao_26, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPOpcao_32, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(JPOpcao_30, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPOpcao_33, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPOpcao_31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPOpcao_37, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(JPOpcao_35, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPOpcao_34, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(JPOpcao_36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(JPOpcao_38, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_39, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPOpcao_32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JPOpcao_27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPOpcao_26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPOpcao_30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPOpcao_39, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPOpcao_33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPOpcao_38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_31, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JPOpcao_34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPOpcao_35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPOpcao_37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPOpcao_36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JPOpcao_26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseEntered

    private void JPOpcao_26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseExited

    private void JPOpcao_26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MousePressed

    private void tf_EnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_Endereco);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_EnderecoMouseClicked

    private void tf_EnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseEntered

    private void tf_EnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseExited

    private void tf_EnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_EnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoKeyReleased

    private void JPOpcao_27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseEntered

    private void JPOpcao_27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseExited

    private void JPOpcao_27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MousePressed

    JPanel jp_Identificador_IP_Web_Servidor; 
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );             
            jp_Identificador_IP_Web_Servidor = new JPanel( new BorderLayout() );  
            Home.adicionar_Tela_De_Trabalho("Identificador IP Web Servidor", jp_Identificador_IP_Web_Servidor);
            enviar_mensagem();
            enviar_ip();
        } catch( Exception e ){ e.printStackTrace(); } } }.start();
    }//GEN-LAST:event_jLabel1MousePressed

    public void enviar_ip() {                                     

        while(true){
            new Thread() {   @Override public void run() { try {             
                Thread.sleep( 120000 ); 
                jp_Identificador_IP_Web_Servidor.removeAll();
                validate();
                enviar_mensagem();
            } catch( Exception e ){ e.printStackTrace(); } } }.start();
        }
    } 
    
    private void JPOpcao_30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MouseEntered

    private void JPOpcao_30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MouseExited

    private void JPOpcao_30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MousePressed

    private void tf_SenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaMouseClicked

    private void tf_SenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaMouseEntered

    private void tf_SenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaMouseExited

    private void tf_SenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_SenhaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaKeyReleased

    private void JPOpcao_31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_31MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_31MouseEntered

    private void JPOpcao_31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_31MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_31MouseExited

    private void JPOpcao_31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_31MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_31MousePressed

    private void JPOpcao_32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_32MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_32MouseEntered

    private void JPOpcao_32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_32MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_32MouseExited

    private void JPOpcao_32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_32MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_32MousePressed

    private void tf_Endereco3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco3MouseClicked

    private void tf_Endereco3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco3MouseEntered

    private void tf_Endereco3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco3MouseExited

    private void tf_Endereco3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Endereco3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco3KeyReleased

    private void JPOpcao_33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_33MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_33MouseEntered

    private void JPOpcao_33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_33MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_33MouseExited

    private void JPOpcao_33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_33MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_33MousePressed

    private void tf_Endereco4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco4MouseClicked

    private void tf_Endereco4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco4MouseEntered

    private void tf_Endereco4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco4MouseExited

    private void tf_Endereco4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Endereco4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco4KeyReleased

    private void JPOpcao_34MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_34MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_34MouseEntered

    private void JPOpcao_34MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_34MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_34MouseExited

    private void JPOpcao_34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_34MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_34MousePressed

    private void JPOpcao_35MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_35MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_35MouseEntered

    private void JPOpcao_35MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_35MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_35MouseExited

    private void JPOpcao_35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_35MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_35MousePressed

    private void tf_Endereco5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco5MouseClicked

    private void tf_Endereco5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco5MouseEntered

    private void tf_Endereco5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco5MouseExited

    private void tf_Endereco5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Endereco5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco5KeyReleased

    private void JPOpcao_36MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_36MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_36MouseEntered

    private void JPOpcao_36MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_36MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_36MouseExited

    private void JPOpcao_36MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_36MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_36MousePressed

    private void JPOpcao_37MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_37MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_37MouseEntered

    private void JPOpcao_37MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_37MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_37MouseExited

    private void JPOpcao_37MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_37MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_37MousePressed

    private void JPOpcao_38MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_38MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_38MouseEntered

    private void JPOpcao_38MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_38MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_38MouseExited

    private void JPOpcao_38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_38MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_38MousePressed

    private void tf_SenhaEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaEmailMouseClicked

    private void tf_SenhaEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaEmailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaEmailMouseEntered

    private void tf_SenhaEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SenhaEmailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaEmailMouseExited

    private void tf_SenhaEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_SenhaEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SenhaEmailKeyReleased

    private void JPOpcao_39MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_39MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_39MouseEntered

    private void JPOpcao_39MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_39MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_39MouseExited

    private void JPOpcao_39MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_39MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_39MousePressed
    
    BrowserFX BrowserFX;
    List<String> list_cmd;
    List<File> fileMails;
    public void enviar_mensagem(){        
        /*new Thread() {   @Override public void run() {*/ try { 

        String destinatario  = "jmarysystems0001@gmail.com";
        String assunto = "0123456789";
        String login   = "jmarysystems0001@gmail.com";
        String pass    = tf_SenhaEmail.getText().trim();
        
        list_cmd = new ArrayList();
        list_cmd.add(destinatario);                               //Destinatário "jmarysystems@gmail.com"
        list_cmd.add( pass );                                  //Senha //"subzero3463"
        list_cmd.add( login );                    //E-mail //"subzero3463.01@gmail.com"  -  "pretim21@gmail.com"
        list_cmd.add( "Cleilson Henrique de Araujo" );          //nome do remetente do email //"subzero3463.01"
        list_cmd.add( assunto ); 
        
        fileMails = new ArrayList<File>();                       //lista contendo os arquivos anexos
        String arquivo1 = "/anexos/CLEILSON_HENRIQUE_DE_ARAUJO" + ".pdf";
        fileMails.add(new File(arquivo1));
                       
        BrowserFX = new BrowserFX( tf_Endereco.getText().trim(),true,true,true, new JButton() );
        jp_Identificador_IP_Web_Servidor.add( BrowserFX, BorderLayout.CENTER );        
        
        Thread.sleep( 20000 );     
        Platform.runLater(new Runnable() {
           @Override
            public void run() {
                BrowserFX.eng.executeScript( "document.getElementById('username').value = 'Admin'" );
                BrowserFX.eng.executeScript( "document.getElementById('password').value = '" + tf_Senha.getText().trim() + "'" );
                BrowserFX.eng.executeScript( "document.getElementById('loginBtn').click()" ); 
            }
        });
        
        Thread.sleep( 15000 ); 
        Platform.runLater(new Runnable() {
           @Override
            public void run() {
                BrowserFX.eng.executeScript( "window.location.href = 'http://192.168.0.1/status.htm';" ); 
            }
        }); 
        
        Thread.sleep( 10000 ); 
        Platform.runLater(new Runnable() {
           @Override
            public void run() {
                String enderecoX = BrowserFX.eng.getLocation();
                System.out.println("enderecoX: " + enderecoX);
                String endereco = "http://192.168.0.1/status.htm?username='Admin'&password='23071354'";
                String html = (String) BrowserFX.eng.executeScript("document.documentElement.outerHTML");
                //System.out.println(html);
                webClient_HtmlUnit( html, list_cmd, fileMails );
            }
        });      
        
        } catch( Exception e ){ e.printStackTrace(); JOPM JOPM = new JOPM( "MÉTODO: " + "criar_mensagem_e_setar_remetentes()\n"
                    ,"\nErro ao tentar criar_mensagem_e_setar_remetentes" 
                    ,this.getClass().getName() ); 
        } //} }.start();                 
    }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_26;
    private javax.swing.JPanel JPOpcao_27;
    private javax.swing.JPanel JPOpcao_30;
    private javax.swing.JPanel JPOpcao_31;
    private javax.swing.JPanel JPOpcao_32;
    private javax.swing.JPanel JPOpcao_33;
    private javax.swing.JPanel JPOpcao_34;
    private javax.swing.JPanel JPOpcao_35;
    private javax.swing.JPanel JPOpcao_36;
    private javax.swing.JPanel JPOpcao_37;
    private javax.swing.JPanel JPOpcao_38;
    private javax.swing.JPanel JPOpcao_39;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JPanel jPanel28;
    public javax.swing.JTextField tf_Endereco;
    public javax.swing.JTextField tf_Endereco3;
    public javax.swing.JTextField tf_Endereco4;
    public javax.swing.JTextField tf_Endereco5;
    public javax.swing.JTextField tf_Senha;
    public javax.swing.JTextField tf_SenhaEmail;
    // End of variables declaration//GEN-END:variables
    
    String ip = "";
    public void webClient_HtmlUnit(String html, List<String> list_cmd, List<File> fileMails){  
        /*new Thread() {   @Override public void run() {*/ try { 
        ip = "";    
   
        StringTokenizer st1=new StringTokenizer(html,"\n");
        for (int i = 0; st1.hasMoreTokens(); i++) {
            String row = ""; try{ row = st1.nextToken(); }catch( Exception e ){} 
            if(i == 227 ){
                
                //System.out.println(i + " - " + row);
                StringTokenizer st2=new StringTokenizer(row,"</b>");
                for (int j = 0; st2.hasMoreTokens(); j++) {
                    String row_parte = ""; try{ row_parte = st2.nextToken(); }catch( Exception e ){} 
                    //System.out.println(j + " - " + row_parte);
                    if(j == 2 ){
                        ip = row_parte.trim();
                        System.out.println(j + " - " + row_parte);
                        Email_Enviar Email_Enviar = new Email_Enviar( list_cmd, fileMails, ip, this ); 
                    }
                }
            }
        }        
        
        } catch( Exception e ){ e.printStackTrace(); JOPM JOPM = new JOPM( "MÉTODO: " + "criar_mensagem_e_setar_remetentes()\n"
                    ,"\nErro ao tentar criar_mensagem_e_setar_remetentes" 
                    ,this.getClass().getName() ); 
        } //} }.start(); 
    }
    
}